name: News Data Collection

on:
  push:
    branches:
      - minkyeong  # minkyeong 브랜치에서만 실행
  workflow_dispatch:  # 수동 실행 허용
  schedule:
    # 매일 23시(UTC) 실행
    - cron: '0 23 * * *'

jobs:
  collect_news_data:
    runs-on: ubuntu-latest
    
    steps:
      # 코드 체크아웃 (minkyeong 브랜치)
      - name: Checkout code
        uses: actions/checkout@v3

      # Python 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      # 요구 사항 설치 (requirements.txt)
      - name: Install dependencies
        run: |
          cd news_chatbot  # news_chatbot 폴더로 이동
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
   # GitHub Actions Runner IP를 MongoDB Atlas에 추가
      - name: Add GitHub Actions Runner IP to Atlas
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          public-api-key: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
          private-api-key: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
          add-current-ip: true

      # mongodb.py 실행
      - name: Run mongodb.py script
        env:
          MONGO_URI: ${{ secrets.MONGO_URL }}  # GitHub Secrets에서 MONGO_URI를 환경 변수로 설정
        run: |
          cd news_chatbot  # news_chatbot 폴더로 이동
          python mongodb.py  # mongodb.py 파일 실행
