name: Manage MongoDB Atlas Access

on:
  push:
    branches:
      - main

jobs:
  manage-access:
    runs-on: ubuntu-latest

    steps:
      # 1. 현재 러너의 공용 IP 가져오기
      - name: Get the public IP of this runner
        id: get-ip
        run: |
          echo "ip-address=$(curl https://checkip.amazonaws.com)" >> "$GITHUB_OUTPUT"

      # 2. MongoDB Atlas API로 러너의 IP 추가
      - name: Permit the runner to access MongoDB Atlas
        id: allow-ip
        run: |
          curl \
            --data '[{"ipAddress": "${{ steps.get-ip.outputs.ip-address }}", "comment": "GitHub Actions Runner"}]' \
            --digest \
            --header 'Accept: application/vnd.atlas.2023-02-01+json' \
            --header 'Content-Type: application/json' \
            --user "$USERNAME:$PASSWORD" \
            "https://cloud.mongodb.com/api/atlas/v2/groups/$GROUP_ID/accessList"
        env:
          GROUP_ID: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}
          PASSWORD: ${{ secrets.ATLAS_PRIVATE_KEY }}
          USERNAME: ${{ secrets.ATLAS_PUBLIC_KEY }}

      # 3. 작업 완료 후 MongoDB 화이트리스트에서 러너의 IP 제거
      - name: Revoke the runner's access to MongoDB Atlas
        if: always() && steps.allow-ip.outcome == 'success'
        run: |
          curl \
            --digest \
            --header 'Accept: application/vnd.atlas.2023-02-01+json' \
            --request 'DELETE' \
            --user "$USERNAME:$PASSWORD" \
            "https://cloud.mongodb.com/api/atlas/v2/groups/$GROUP_ID/accessList/${{ steps.get-ip.outputs.ip-address }}"
        env:
          GROUP_ID: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}
          PASSWORD: ${{ secrets.ATLAS_PRIVATE_KEY }}
          USERNAME: ${{ secrets.ATLAS_PUBLIC_KEY }}
